BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TB_USER" (
	"Num"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"SSN"	TEXT,
	"EMAIL"	TEXT,
	"Status"	INTEGER,
	"RefCode"	TEXT,
	"SecretNum"	TEXT
);
CREATE TABLE IF NOT EXISTS "TB_CERT" (
	"Num"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"KeyNum"	INTEGER,
	"UserNum"	INTEGER,
	"signAlg"	TEXT,
	"Cert"	TEXT,
	"IsSelf"	INTEGER,
	"IsCA"	INTEGER,
	"IssuerNum"	INTEGER,
	"SubjectDN"	TEXT,
	"Status"	INTEGER,
	"Serial"	TEXT,
	"DNHash"	TEXT,
	"KeyHash"	TEXT
);
CREATE TABLE IF NOT EXISTS "TB_SIGNER" (
	"Num"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Type"	INTEGER,
	"DN"	TEXT,
	"DNHash"	TEXT,
	"Status"	INTEGER,
	"Cert"	TEXT,
	"Desc"	TEXT
);
CREATE TABLE IF NOT EXISTS "TB_CERT_POLICY" (
	"NUM"	INTEGER,
	"Name"	TEXT,
	"Version"	INTEGER,
	"NotBefore"	INTEGER,
	"NotAfter"	INTEGER,
	"Hash"	TEXT,
	"DNTemplate"	TEXT,
	PRIMARY KEY("NUM")
);
CREATE TABLE IF NOT EXISTS "TB_CRL_POLICY" (
	"Num"	INTEGER,
	"Name"	TEXT,
	"Version"	INTEGER,
	"LastUpdate"	INTEGER,
	"NextUpdate"	INTEGER,
	"Hash"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_REQ" (
	"SEQ"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"KEY_NUM"	INTEGER,
	"NAME"	TEXT,
	"DN"	TEXT,
	"CSR"	TEXT,
	"HASH"	TEXT,
	"Status"	INTEGER
);
CREATE TABLE IF NOT EXISTS "TB_KEY_PAIR" (
	"NUM"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"ALGORITHM"	TEXT,
	"NAME"	Text,
	"PUBLIC"	Text,
	"PRIVATE"	Text,
	"PARAM"	Text,
	"Status"	INTEGER
);
CREATE TABLE IF NOT EXISTS "TB_REVOKED" (
	"Seq"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"CertNum"	INTEGER,
	"IssuerNum"	INTEGER,
	"Serial"	TEXT,
	"RevokedDate"	INTEGER,
	"Reason"	INTEGER
);
CREATE TABLE IF NOT EXISTS "TB_CRL" (
	"Num"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"IssuerNum"	INTEGER,
	"signAlg"	TEXT,
	"CRL"	TEXT
);
CREATE TABLE IF NOT EXISTS "TB_CRL_POLICY_EXTENSION" (
	"Seq"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"PolicyNum"	INTEGER,
	"Critical"	INTEGER,
	"SN"	TEXT,
	"Value"	TEXT
);
CREATE TABLE IF NOT EXISTS "TB_CERT_POLICY_EXTENSION" (
	"Seq"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"PolicyNum"	INTEGER,
	"Critical"	INTEGER,
	"SN"	TEXT,
	"Value"	TEXT
);
COMMIT;
