BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TB_SEQ" (
	"seq"	INTEGER,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("name")
);
CREATE TABLE IF NOT EXISTS "TB_USER" (
	"Num"	INTEGER,
	"RegTime"	INTEGER,
	"Name"	TEXT,
	"SSN"	TEXT,
	"EMAIL"	TEXT,
	"Status"	INTEGER,
	"RefNum"	TEXT,
	"AuthCode"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_TSP" (
	"SEQ"	INTEGER NOT NULL UNIQUE,
	"RegTime"	INTEGER,
	"Serial"	INTEGER,
	"SrcHash"	TEXT,
	"Policy"	TEXT,
	"TSTInfo"	TEXT,
	"Data"	TEXT,
	PRIMARY KEY("SEQ")
);
CREATE TABLE IF NOT EXISTS "TB_SIGNER" (
	"Num"	INTEGER,
	"RegTime"	INTEGER,
	"Type"	INTEGER,
	"DN"	TEXT,
	"DNHash"	TEXT,
	"Status"	INTEGER,
	"Cert"	TEXT,
	"Info"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_REQ" (
	"SEQ"	INTEGER,
	"REGTIME"	INTEGER,
	"KEY_NUM"	INTEGER,
	"NAME"	TEXT,
	"DN"	TEXT,
	"CSR"	TEXT,
	"HASH"	TEXT,
	"Status"	INTEGER,
	PRIMARY KEY("SEQ")
);
CREATE TABLE IF NOT EXISTS "TB_KEY_PAIR" (
	"NUM"	INTEGER NOT NULL UNIQUE,
	"RegTime"	INTEGER,
	"ALGORITHM"	TEXT,
	"NAME"	Text,
	"PUBLIC"	Text,
	"PRIVATE"	Text,
	"PARAM"	Text,
	"Status"	INTEGER,
	PRIMARY KEY("NUM")
);
CREATE TABLE IF NOT EXISTS "TB_REVOKED" (
	"Seq"	INTEGER,
	"CertNum"	INTEGER,
	"IssuerNum"	INTEGER,
	"Serial"	TEXT,
	"RevokedDate"	INTEGER,
	"Reason"	INTEGER,
	"CRLDP"	TEXT,
	PRIMARY KEY("Seq")
);
CREATE TABLE IF NOT EXISTS "TB_KMS" (
	"SEQ"	INTEGER NOT NULL UNIQUE,
	"REGTIME"	INTEGER,
	"STATUS"	INTEGER,
	"TYPE"	INTEGER,
	"ALGORITHM"	INTEGER,
	"ID"	TEXT,
	"INFO"	TEXT,
	PRIMARY KEY("SEQ")
);
CREATE TABLE IF NOT EXISTS "TB_CRL_PROFILE_EXTENSION" (
	"Seq"	INTEGER,
	"ProfileNum"	INTEGER,
	"Critical"	INTEGER,
	"SN"	TEXT,
	"Value"	TEXT,
	PRIMARY KEY("Seq")
);
CREATE TABLE IF NOT EXISTS "TB_CRL" (
	"Num"	INTEGER,
	"RegTime"	INTEGER,
	"IssuerNum"	INTEGER,
	"signAlg"	TEXT,
	"CRLDP"	TEXT,
	"CRL"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_CONFIG" (
	"Num"	INTEGER,
	"Kind"	INTEGER,
	"Name"	TEXT,
	"Value"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_CERT_PROFILE_EXTENSION" (
	"Seq"	INTEGER,
	"ProfileNum"	INTEGER,
	"Critical"	INTEGER,
	"SN"	TEXT,
	"Value"	TEXT,
	PRIMARY KEY("Seq")
);
CREATE TABLE IF NOT EXISTS "TB_CERT" (
	"Num"	INTEGER,
	"RegTime"	INTEGER,
	"KeyNum"	INTEGER,
	"UserNum"	INTEGER,
	"signAlg"	TEXT,
	"Cert"	TEXT,
	"IsSelf"	INTEGER,
	"IsCA"	INTEGER,
	"IssuerNum"	INTEGER,
	"SubjectDN"	TEXT,
	"Status"	INTEGER,
	"Serial"	TEXT,
	"DNHash"	TEXT,
	"KeyHash"	TEXT,
	"CRLDP"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_AUDIT" (
	"Seq"	INTEGER NOT NULL,
	"RegTime"	INTEGER,
	"Kind"	INTEGER,
	"Operation"	INTEGER,
	"UserName"	TEXT,
	"Info"	TEXT,
	"MAC"	TEXT,
	PRIMARY KEY("Seq")
);
CREATE TABLE IF NOT EXISTS "TB_ADMIN" (
	"Seq"	INTEGER,
	"Name"	TEXT,
	"Password"	TEXT,
	"Status"	INTEGER,
	"Email"	TEXT,
	"Type"	INTEGER,
	PRIMARY KEY("Seq")
);
CREATE TABLE IF NOT EXISTS "TB_CERT_PROFILE" (
	"NUM"	INTEGER,
	"Name"	TEXT,
	"Type"	INTEGER,
	"Version"	INTEGER,
	"NotBefore"	INTEGER,
	"NotAfter"	INTEGER,
	"ExtUsage"	INTEGER,
	"Hash"	TEXT,
	"DNTemplate"	TEXT,
	PRIMARY KEY("NUM")
);
CREATE TABLE IF NOT EXISTS "TB_CRL_PROFILE" (
	"Num"	INTEGER,
	"Name"	TEXT,
	"Version"	INTEGER,
        "ThisUpdate"	INTEGER,
	"NextUpdate"	INTEGER,
	"Hash"	TEXT,
	PRIMARY KEY("Num")
);
CREATE TABLE IF NOT EXISTS "TB_AUTH" (
	"Token"	TEXT,
	"UserName"	TEXT,
	"RegTime"	INTEGER,
	"Valid"	INTEGER
);
COMMIT;
