-- DROP TABLE TB_CRL_PROFILE_EXTENSION;
-- DROP TABLE TB_CERT_PROFILE_EXTENSION;
-- DROP TABLE TB_KMS;
-- DROP TABLE TB_KMS_ATTRIB;
-- DROP TABLE TB_CRL;
-- DROP TABLE TB_ADMIN;
-- DROP TABLE TB_TSP;
-- DROP TABLE TB_REQ;
-- DROP TABLE TB_KEY_PAIR;
-- DROP TABLE TB_AUDIT;
-- DROP TABLE TB_CERT_PROFILE;
-- DROP TABLE TB_CRL_PROFILE;
-- DROP TABLE TB_SIGNER;
-- DROP TABLE TB_USER;
-- DROP TABLE TB_CERT;
-- DROP TABLE TB_AUTH;
-- DROP TABLE TB_REVOKED;
-- DROP TABLE TB_CONFIG;
-- DROP TABLE TB_SEQ;
-- DROP TABLE TB_LICENSE;


CREATE TABLE IF NOT EXISTS TB_CRL_PROFILE_EXTENSION (
 Seq   INT NOT NULL,
 ProfileNum INT,
 Critical INT,
 SN   VARCHAR(64),
 Value  VARCHAR(512),
 PRIMARY KEY(Seq)
);

CREATE TABLE IF NOT EXISTS TB_CERT_PROFILE_EXTENSION (
 Seq INT NOT NULL,
 ProfileNum INT,
 Critical INT,
 SN VARCHAR(64),
 Value VARCHAR(512),
 PRIMARY KEY(Seq) 
);


CREATE TABLE IF NOT EXISTS TB_KMS (
 SEQ INT NOT NULL PRIMARY KEY UNIQUE,
 REGTIME INT,
 STATE INT,
 TYPE INT,
 ALGORITHM INT,
 ID VARCHAR(256),
 INFO VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS TB_KMS_ATTRIB (
 NUM INT,
 TYPE INT,
 VALUE VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_CRL (
 Num INT PRIMARY KEY,
 RegTime INT,
 IssuerNum INT,
 ThisUpdate INT,
 NextUpdate INT,
 signAlg VARCHAR(256),
 CRLDP VARCHAR(256),
 CRL Text
);

CREATE TABLE IF NOT EXISTS TB_ADMIN (
 Seq INT PRIMARY KEY,
 Status INT,
 Type INT,
 Name VARCHAR(256),
 Password VARCHAR(256),
 Email VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_TSP (
 SEQ INT NOT NULL PRIMARY KEY UNIQUE,
 RegTime INT,
 Serial INT,
 SrcHash VARCHAR(256),
 Policy VARCHAR(256),
 TSTInfo VARCHAR(256),
 Data VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_REQ (
 SEQ INT PRIMARY KEY,
 REGTIME INT,
 KEY_NUM INT,
 NAME VARCHAR(256),
 DN VARCHAR(256),
 CSR Text,
 HASH VARCHAR(256),
 Status INT
);

CREATE TABLE IF NOT EXISTS TB_KEY_PAIR (
 NUM INT NOT NULL PRIMARY KEY,
 RegTime INT,
 ALGORITHM VARCHAR(256),
 NAME VARCHAR(256),
 PUBLIC Text,
 PRIVATE Text,
 PARAM VARCHAR(256),
 Status INT
);

CREATE TABLE IF NOT EXISTS TB_AUDIT (
 Seq INT NOT NULL PRIMARY KEY,
 RegTime INT,
 Kind INT,
 Operation INT,
 UserName VARCHAR(256),
 Info VARCHAR(256),
 MAC VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS TB_CERT_PROFILE (
 NUM INT,
 Name VARCHAR(256),
 Type INT,
 Version INT,
 NotBefore INT,
 NotAfter INT,
 ExtUsage INT,
 Hash VARCHAR(256),
 DNTemplate VARCHAR(256),
 PRIMARY KEY(NUM)
);


CREATE TABLE IF NOT EXISTS TB_CRL_PROFILE (
 Num INT,
 Name VARCHAR(256),
 Version INT,
 ThisUpdate INT,
 NextUpdate INT,
 Hash VARCHAR(256),
 PRIMARY KEY(Num)
);

CREATE TABLE IF NOT EXISTS TB_SIGNER (
 Num INT PRIMARY KEY,
 RegTime INT,
 Type INT,
 DN VARCHAR(256),
 DNHash VARCHAR(256),
 Status INT,
 Cert Text,
 Info VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_USER (
 Num INT PRIMARY KEY,
 RegTime INT,
 Name VARCHAR(256),
 SSN VARCHAR(256),
 EMAIL VARCHAR(256),
 Status INT,
 RefNum VARCHAR(256),
 AuthCode VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_CERT (
 Num INT PRIMARY KEY,
 RegTime INT,
 KeyNum INT,
 UserNum INT,
 signAlg VARCHAR(256),
 Cert Text,
 IsSelf INT,
 IsCA INT,
 IssuerNum INT,
 SubjectDN VARCHAR(256),
 Status INT,
 Serial VARCHAR(256),
 DNHash VARCHAR(256),
 KeyHash VARCHAR(256),
 CRLDP VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS TB_AUTH (
 Token VARCHAR(256),
 UserName VARCHAR(256),
 RegTime INT,
 Valid INT
);

CREATE TABLE IF NOT EXISTS TB_REVOKED (
 Seq INT PRIMARY KEY,
 CertNum INT,
 IssuerNum INT,
 Serial VARCHAR(256),
 RevokedDate INT,
 Reason INT,
 CRLDP VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_CONFIG (
 Num INT PRIMARY KEY,
 Kind INT,
 Name VARCHAR(256),
 Value VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TB_SEQ (
 Seq INT,
 Name VARCHAR(256),
 PRIMARY KEY(Name)
);

CREATE TABLE IF NOT EXISTS TB_LICENSE (
 Seq INT PRIMARY KEY,
 RegTime INT,
 Status INT,
 Type INT,
 QTY INT,
 SID VARCHAR(128),
 User VARCHAR(128),
 Issued VARCHAR(32),
 Expire VARCHAR(32),
 Product VARCHAR(128),
 Ref VARCHAR(128),
 Ext VARCHAR(128),
 AuthKey VARCHAR(128),
 License VARCHAR(2048)
);
